### ISSUE TITLE
Test with long release names

### ISSUE THREAD

**Issue by cevian** [timescale/timescale-observability#11]
One error people get is:

helm install timescale-observability  timescale/timescale-observability --devel
Error: CronJob.batch "timescale-observability-timescale-prometheus-drop-chunk" is invalid: metadata.name: Invalid value: "timescale-observability-timescale-prometheus-drop-chunk": must be no more than 52 characters.

**Comment by ismailyenigul** [comment]
You can also trim the long names
An example from https://www.ibm.com/cloud/architecture/content/course/helm-fundamentals/chart-template-helpers


```
{/* vim: set filetype=mustache: */}}
{{/* Expand the name of the chart. */}}
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{/* Create a default fully qualified app name. We truncate at 63 chars because . . . */}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
